### ISSUE TITLE
Support for spatial constructing functions.

### ISSUE THREAD

**Issue by milos-colic** [databrickslabs/mosaic#10]
**Is your feature request related to a problem? Please describe.**
Allow users to generate new spatial objects.

ST_MakePoint
ST_MakeLine
ST_MakePolygon
ST_Buffer
ST_Envelope
ST_MakeMultiPoint

**Comment by milos-colic** [comment]
These are already implemented. Closing the item.

**Comment by gah112** [comment]
ST_Envelope is not implemented and would be very useful.

**Comment by sllynn** [comment]
👍 Good point @gah112. I've added it to our backlog.

**Comment by gah112** [comment]
@sllynn any update on this one?

**Comment by edurdevic** [comment]
Hi @gah112, we are picking up st_* functions again now.
ST_Envelope is on the list, it might make it in a few couple of weeks.
