### ISSUE TITLE
Using Mosaic outside Databricks for unit-testing Python code

### ISSUE THREAD

**Issue by nicolattuso** [databrickslabs/mosaic#115]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run my code using Mosaic in local. Currently, I have tests for my pyspark code, and as I am adding new transformations that use Mosaic I would like to unit-test those as well.

**Describe the solution you'd like**
A documented way of running Mosaic in local for unit-testing

**Additional context**
Here is the full log for running `enable_mosaic(spark_session)` in local, including the error I get:

```
22/05/18 12:00:23 INFO MosaicLibraryHandler: Looking for Mosaic JAR at /home/nicolas/.pyenv/versions/myenv/lib/python3.9/site-packages/mosaic/lib/mosaic-0.1.1-jar-with-dependencies.jar.
22/05/18 12:00:23 INFO MosaicLibraryHandler: Automatically attaching Mosaic JAR to cluster.
Traceback (most recent call last):
  File "/home/nicolas/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e83e439e0633>", line 1, in <module>
    enable_mosaic(spark_session)
  File "/home/nicolas/.pyenv/versions/myenv/lib/python3.9/site-packages/mosaic/api/enable.py", line 47, in enable_mosaic
    _ = MosaicLibraryHandler(config.mosaic_spark)
  File "/home/nicolas/.pyenv/versions/myenv/lib/python3.9/site-packages/mosaic/core/library_handler.py", line 29, in __init__
    self.auto_attach()
  File "/home/nicolas/.pyenv/versions/myenv/lib/python3.9/site-packages/mosaic/core/library_handler.py", line 76, in auto_attach
    ManagedLibraryId.defaultOrganization(),
TypeError: 'JavaPackage' object is not callable
```

**Comment by edurdevic** [comment]
This is described in the [Contributing](https://github.com/databrickslabs/mosaic/blob/main/CONTRIBUTING.md) section.
But this is a good feedback, we should include at least a link to it from the Readme.

**Comment by nicolattuso** [comment]
Just to be clear: I am not trying to run Mosaic's tests, I am trying to test **my own code** that uses Mosaic. I read the Contributing section, and it does not tell me how to do that (it tells me how to test **Mosaic**, which is indeed what I expect from a Contributing section).

In the meantime, I came up with a way of testing my own code. When I changed the spark configuration as below the problem disappeared.

```python
spark_session = (
    SparkSession.builder.master("local[*]")
    .config(
        "spark.jars",
        f"{os.environ['VIRTUAL_ENV']}/lib/python3.9/site-packages/"
        "mosaic/lib/mosaic-0.1.1-jar-with-dependencies.jar",
    )
    .config("spark.databricks.labs.mosaic.jar.autoattach", False)
    .appName("mylib-tests")
    .getOrCreate()
)
enable_mosaic(spark_session)  # works
```

However, I feel that referencing a jar file inside my python virtual environment is not very clean. Maybe there is a better way?

**Comment by sllynn** [comment]
@nicolattuso How did you install Mosaic? Did you take the python whl from the release section and install that?

**Comment by nicolattuso** [comment]
@sllynn Yes, this is what I did.

**Comment by edurdevic** [comment]
You can now use `pip install databricks-mosaic`
