### ISSUE TITLE
New function: st_concavehull

### ISSUE THREAD

**Issue by JesseKHall** [databrickslabs/mosaic#117]
**Is your feature request related to a problem? Please describe.**
There is not a native way to find the concave hull around a geometry or multi-geometry object.

**Describe the solution you'd like**
A built in function to calculate the concave hull.

**Describe alternatives you've considered**
There are other libraries that have this functionality, but it'd be great to have it included in mosaic natively.

**Comment by sllynn** [comment]
@JesseKHall Our blocker with this is that there's no function for computing concave hulls in either of the underlying geometry APIs. If you a reference implementation, please share.
