### ISSUE TITLE
Support for additional spatial input/output functions.

### ISSUE THREAD

**Issue by sllynn** [databrickslabs/mosaic#14]
**Is your feature request related to a problem? Please describe.**
Allow users to work with a common spatial storage format Geohash.

ST_GeogFromGeohash
ST_GeomFromGeohash
ST_Geohash

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by milos-colic** [comment]
Closing this issue, since we will have a PR covering the full extent of geohash. Makes more sense to track it as a part of that feature.
