### ISSUE TITLE
New Feature - Add Support for File Geodatabase IO

### ISSUE THREAD

**Issue by armckinney** [databrickslabs/mosaic#141]
**Is your feature request related to a problem? Please describe.**
Many sources for spatial data are formatted and provided as file geodatabases (.gdb). Currently, there are no spark-native  utilities that offer file geodatabase input/output operations. 

**Describe the solution you'd like**
Implement the [OpenFileGDB driver](https://gdal.org/drivers/vector/openfilegdb.html#vector-openfilegdb) and expose Read (and Write) IO API operations.

**Describe alternatives you've considered**
A current python-based workaround is to utilize [geopandas](https://geopandas.org/en/stable/#) as an ingestion tool prior to converting to a Spark DataFrame; however, this utilizes pandas dataframes which load entirely into memory. This is a slow and expensive operation, as it also means that driver nodes must be scaled large enough to hold entire datasets in memory.
Aggregate [masked/row-filtered loads](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html#geopandas.read_file) can be completed as well to speed up and remedy some of these issues, but this can be a complicated process to orchestrate and manage fractionalized loads without prior dataset knowledge.

**Comment by milos-colic** [comment]
Added in v0.3.8+ via
`mos.read()
.format("multi_read_ogr")
.load(dir_path)`
