### ISSUE TITLE
h3 glibc error

### ISSUE THREAD

**Issue by rsdavis** [databrickslabs/mosaic#167]
**Describe the bug**
I'm hitting an error when I run `mosaic_explode` in a Databricks notebook. Seems to be related to a dependency change within h3.  glibc did not get pinned. https://github.com/uber/h3-java/issues/85

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2173.0 failed 4 times, most recent failure: Lost task 0.4 in stage 2173.0 (TID 133372) (10.162.219.95 executor 460): java.lang.UnsatisfiedLinkError: /local_disk0/tmp/libh3-java7309423786443199069.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /local_disk0/tmp/libh3-java7309423786443199069.so)
```

I'm not sure if this is something I need to fix on my end, or if it's a matter of bumping the dependency. Feel free to close, thanks.

**To Reproduce**
```
import com.databricks.labs.mosaic.functions.MosaicContext
import com.databricks.labs.mosaic.H3
import com.databricks.labs.mosaic.JTS

val mosaicContext = MosaicContext.build(H3, JTS)
import mosaicContext.functions.mosaic_explode

val df = Seq("POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))")
  .toDF("geometry")
  .withColumn("index", mosaic_explode($"geometry", 7))

display(df)
```

**Expected behavior**
Runs without error

**Additional context**
Also happens when using `point_index_geom`
I'm using latest `mosaic_0_2_0_jar_with_dependencies.jar`

**Comment by edurdevic** [comment]
Thanks for reporting this @rsdavis.
We are solving this in the next release.

**Comment by edurdevic** [comment]
@rsdavis Which version of the Databricks Runtime are you using?

**Comment by edurdevic** [comment]
Mosaic requires Databricks Runtime (DBR) version 10.0 or higher (so Spark 3.2.1 or higher).
I was able to reproduce your error with DBR 7.3, which is not supported.

**Comment by rsdavis** [comment]
Ok, that makes sense, I'm on DBR 8.1 which using Spark 3.1.1
