### ISSUE TITLE
How to properly install mosaic on cluster with docker image

### ISSUE THREAD

**Issue by ojabri1** [databrickslabs/mosaic#194]
I am creating a cluster with databricks api and I want to install databricks-mosaic on the cluster
I tried to install it following the doc [here](https://databrickslabs.github.io/mosaic/usage/installation.html)

I have an error when enabling the Mosaic functions with `enable_mosaic(spark_session)`
`java.nio.charset.MalformedInputException: Input length = 1`

<img width="344" alt="image" src="https://user-images.githubusercontent.com/58430896/186356842-00e614ef-bbd2-408d-b1ab-ac95c2c884d8.png">

When I install mosaic in an interactive notebook with `%pip install databricks-mosaic` it works fine but I need to install it for a job

**Comment by edurdevic** [comment]
You can install mosaic like any other pip library in your job configuration
<img width="630" alt="image" src="https://user-images.githubusercontent.com/2878017/186405164-2550ccea-8974-4999-a4d2-922b7b3c5de4.png">

Which DBR version are you running for your job?

**Comment by ojabri1** [comment]
I tried using an init script with 
`#!/bin/bash

/databricks/python/bin/pip install databricks-mosaic`

still the same error, I am using DBR 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12)

**Comment by sebdiem** [comment]
@edurdevic I'm working with @ojabri1 

we get this error when trying to run mosaic on databricks using the databricks 10.4 LTS **docker image**
do you have any idea how we could fix the docker image to make it work ?

**Comment by edurdevic** [comment]
Hi @sebdiem, my apologies for the delay.
We did not test the Docker integration yet, so I don't have a clear answer to this question for now.

Let me explain how it works, I hope this is helpful:
Mosaic is built mainly in Scala, and it uses third-party OSS libraries under the hood for geometry operations (JTS, ESRI, H3, etc.). All of it is packaged in a JAR file, and that needs to be available in the context to work.
When it comes to python and R bindings, they both rely on the JAR being installed in order to work.
We do package the JAR with all its dependencies into the wheel that we ship to pip, so if you %pip install it, that will be unpackaged and be available. The code that does the magic is in the [library_handler](https://github.com/databrickslabs/mosaic/blob/main/python/mosaic/core/library_handler.py).

From the error you shared, it sounds like if is not finding the JAR where it is expected, so you could try to configure that with the Spark conf spark.conf.get("spark.databricks.labs.mosaic.jar.autoattach"), or move it into the right place.

**Comment by sebdiem** [comment]
Hi @edurdevic,
Thanks for the details.
From what I get from the logs of my cluster with docker image, the library seems to be attached correctly.

```
22/10/21 15:36:35 INFO MosaicLibraryHandler: Looking for Mosaic JAR at /databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar.
22/10/21 15:36:35 INFO MosaicLibraryHandler: Automatically attaching Mosaic JAR to cluster.
22/10/21 15:36:35 INFO SharedDriverContext: [Thread 230] attachLibrariesToSpark JavaJarId(file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar,,NONE)
22/10/21 15:36:35 INFO LibraryDownloadManager: Downloading a library that was not in the cache: JavaJarId(file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar,,NONE)
22/10/21 15:36:35 INFO LibraryDownloadManager: Attempt 1: wait until library JavaJarId(file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar,,NONE) is downloaded
22/10/21 15:36:35 INFO LibraryDownloadManager: Downloaded library JavaJarId(file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar,,NONE) as local file /local_disk0/tmp/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar in 21 milliseconds
22/10/21 15:36:35 INFO SharedDriverContext: Successfully saved library JavaJarId(file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar,,NONE) to local file /local_disk0/tmp/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar 
22/10/21 15:36:35 INFO SparkContext: Added file /local_disk0/tmp/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar at spark://10.76.174.219:35219/files/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar with timestamp 1666366595672
22/10/21 15:36:35 INFO Utils: Copying /local_disk0/tmp/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar to /local_disk0/spark-cba20df8-5a68-4ca9-bbde-10fd34780443/userFiles-0721c02e-0ed6-4d4f-bc48-736480d71444/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar
22/10/21 15:36:35 INFO SparkContext: Added JAR /local_disk0/tmp/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar at spark://10.76.174.219:35219/jars/addedFile3848058883183847571mosaic_0_3_0_jar_with_dependencies-d7fba.jar with timestamp 1666366595695
22/10/21 15:36:35 INFO SharedDriverContext: Successfully attached library file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar to Spark
22/10/21 15:36:35 INFO LibraryState: [Thread 230] Successfully attached library file:/databricks/python/lib/python3.8/site-packages/mosaic/lib/mosaic-0.3.0-jar-with-dependencies.jar
```

**Comment by sebdiem** [comment]
hmm setting `spark.driver.extraJavaOptions -Dfile.encoding=utf-8` seems to solve the issue
