### ISSUE TITLE
WKB bug? com.esri.core.geometry.GeometryException: invalid shape type

### ISSUE THREAD

**Issue by torkjetil** [databrickslabs/mosaic#198]
The geometry is from a postgis db we are trying to use. Where it i valid and works fine.
![image](https://user-images.githubusercontent.com/366886/187867396-71f74262-a9f3-495d-adf6-196757feef36.png)

import mosaic as mos
import binascii
hex = '0101000020E9640000401E9C2452A1E3C03212E040F30D5941'
binary = binascii.unhexlify(hex)
df = spark.createDataFrame([{'wkb': binary}])
df.select(mos.st_geomfromwkb('wkb')).show(1, False)

results in com.esri.core.geometry.GeometryException: invalid shape type

%sql
SELECT ST_AsText(ST_GeomFromWKB('0101000020E9640000401E9C2452A1E3C03212E040F30D5941'));

results in Could not parse Well-Known Text around position: 0

**Comment by edurdevic** [comment]
We are using ESRI Geometry APIs by default, and that API does not support the point representation you are passing.

You can use JTS Geometry API instead by setting the following spark configuration
`spark.conf.set("spark.databricks.labs.mosaic.geometry.api", "JTS")` before enabling Mosaic. 

<img width="735" alt="image" src="https://user-images.githubusercontent.com/2878017/187938797-f198a6c8-8e77-489c-a03b-9fa683cfb3db.png">

**Comment by torkjetil** [comment]
Found it needed a little unhex to work.
%sql
SELECT ST_GeomFromWKB(**unhex**('0101000020E9640000401E9C2452A1E3C03212E040F30D5941'));    

and 
.withColumn("geom", mos.st_geomfromwkb(**unhex**(col("representasjonspunkt"))))
