### ISSUE TITLE
Support to write output geospatial files to cloud storage

### ISSUE THREAD

**Issue by syaps1** [databrickslabs/mosaic#218]
**Is your feature request related to a problem? Please describe.**
After performing a spatial join in Mosaic and getting the joined dataframe (similar to the Quickstart notebook's `trips` dataframe [here](https://databrickslabs.github.io/mosaic/usage/quickstart.html#Geometry-clipping-without-an-index): there seems no readily accessible method/way to output the dataframe to a `.geojson` file while preserving the geometries as WKT.

**Describe the solution you'd like**
Is it possible to have a method similar to geopandas' `to_file()` that would write the dataframe to `.geojson`?

**Describe alternatives you've considered**
Converting outright to a geopandas dataframe to use `to_file()` can take a very long time for large datasets. 

Have also tried to save as .csv to do the conversion offline but this gives another error `CSV data source does not support struct>>,holes:array>>>> data type.`. It does not seem possible to remove the `holes` segment from the output.

We can also do the entire spatial join in geopandas and output the file using geopandas to_file (ie. without using Mosaic at all) and this is one workaround.

**Additional context**
Would like to leverage Mosaic to do spatial joins on large datasets (point in polygon operation, where points are lat/longs in a Delta table and polygons are in `.geojsonl` files.) Unfortunately due to downstream requirements we are required to output the join result either as a `.geojson` file or `.shp` where the geometry column has to be the polygon geometry and the point coordinates are saved in another column.

**Contributing to Mosaic**

**Comment by syaps1** [comment]
Hi @milos-colic, thank you very much for the fast response to my query. Am I understanding right, that the main bottleneck would be the coalesce process to combine the partitioned results back into 1 file? 

I noticed that on the main github [page](https://github.com/databrickslabs/mosaic/), the diagram shows that Mosaic I/O with Delta lake tables as the data layer. Would a solution then be, to first output the join result as WKT to a Delta table and then select from the Delta table to convert to `.geojson`? (I am guessing this would benefit from Mosaic to speed up the join but still run into the slowdown/bottleneck issue at the end when converting to geojson.)

**Comment by edurdevic** [comment]
Hi @syaps1, yes indeed.
The recommended architecture is to always use delta tables to store your geometries in a column. 
We recommend using WKT or WKB for all your tables (WKB is more performant), and then on the final stage (your gold layer) convert it in the format you need for your downstream processing.
In this last stage you can have convert a WKT column to geoJSON with [st_asgeojson](https://databrickslabs.github.io/mosaic/api/geometry-accessors.html#st-asgeojson). Then you can save it as a multiline JSON with `dataframe.coalesce(1).write.json("path")`. 
Please note that that will create a geoJSON object on every line in the file, you might need to split it into multiple files (one per line) or convert it into a multiline JSON for your downstream applications.
