### ISSUE TITLE
grid_tessellate returns duplicates

### ISSUE THREAD

**Issue by evisser** [databrickslabs/mosaic#243]
**Describe the bug**
When using the grid_tessellate function to find the h3 hexagons covering a polygon it sometimes happens that the resulting list contains duplicates.

**To Reproduce**
```
%pip install databricks-mosaic=="0.3.3"

import pyspark.sql.functions as F
from mosaic import enable_mosaic
import mosaic as mos

enable_mosaic(spark, dbutils)

df = spark.createDataFrame(data=[{"geometry_wkt": "POLYGON ((4.42 51.78, 4.38 51.78, 4.39 51.83, 4.40 51.83, 4.41 51.8303, 4.417 51.8295, 4.42 51.83, 4.44 51.81, 4.42 51.78))"}])
df = df.withColumn("polyfill_results", mos.polyfill("geometry_wkt", F.lit(7)))
df = df.withColumn("tessellate_results", mos.grid_tessellate("geometry_wkt", F.lit(7)))
df = df.withColumn("tessellate_results", F.array_sort(F.transform("tessellate_results.chips", lambda x: F.struct(x.index_id.alias("index_id"), x.is_core.alias("is_core")))))
df.drop("geometry_wkt").display()
```

**Expected behavior**
No duplicates present in the output of grid_tessellate

**Screenshots**
![image](https://user-images.githubusercontent.com/18210129/199705201-885e5b9f-d311-4240-ac83-c82a309f713c.png)

In the screenshot elements 1 and 2 are the same in the tessellate results.

**Additional context**
Databricks 10.4 LTS (Scala 2.12, Spark version 3.2.1)
mosaic 0.3.3.

It appears that all duplicates have is_core = True. The grid_polyfill function does not return duplicates (see screenshot).

**Comment by edurdevic** [comment]
Thank you for reporting this.
We are looking into it.
