### ISSUE TITLE
Update com.uber.h3 from the current 3.7.0 to at least 3.7.2

### ISSUE THREAD

**Issue by RinatVeliakhmedov-TomTom** [databrickslabs/mosaic#245]
**Is your feature request related to a problem? Please describe.**
I am using a MacBook with M1 chip. Unfortunately, this means that `com.databricks.labs.mosaic.functions.MosaicContext` creation will fail at runtime since it requires `/darwin-arm64/libh3-java.dylib` which is not there. I see that it was added to `h3` in version `3.7.2` 
https://mvnrepository.com/artifact/com.uber/h3/3.7.2
https://github.com/uber/h3-java/commit/6776010b19009dc0690d3b76edc4e1d6345e9910

**Describe the solution you'd like**
I want to be able to run `MosaicContext.init` on my M1 chip machine, therefore I think the easiest way to achieve this is for `mosaic` to update its `uber h3` dependency.

**Describe alternatives you've considered**
I can manually include `com.uber:h3:3.7.2` as a dependency to make it work.

**Additional context**
I'm using `mosaic-0.3.0-jar-with-dependencies.jar`

**Contributing to Mosaic**
Guidelines for contributing to Mosaic can be found in `CONTRIBUTING.md`.

**Comment by edurdevic** [comment]
Thanks for opening this request.
We choose to keep the `3.7.0` in order to be aligned with the current version of the Databricks DBR.
Since we forward the calls that are implemented by the runtime when available, we wanted to have the exact same version.
