### ISSUE TITLE
module 'mosaic.config.config' has no attribute 'mosaic_context'

### ISSUE THREAD

**Issue by abhilshitsoni-tomtom** [databrickslabs/mosaic#275]
**Describe the bug**
Not able to invoke any Mosaic function in a fresh databricks cluster

**To Reproduce**
1. Create a single node cluster in databricks with all default settings
2. Create a new notebook attached to this cluster
3. In the first cell  do `%pip install databricks-mosaic `
4. In second cell do 
`import binascii`
`import mosaic`
`from mosaic import st_geomfromwkb`
`hex = '0000000001C052F1F0ED3D859D4041983D46B26BF8'`
`binary = binascii.unhexlify(hex)`
`df = spark.createDataFrame([{'wkb': binary}])`
`df.select(st_geomfromwkb('wkb')).show(1, False)`
5. It throws the error `module 'mosaic.config.config' has no attribute 'mosaic_context'`

**Expected behavior**
The sample code should execute 

**Screenshots**
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/113018367/206297217-9514f55d-9201-4ced-aecb-5d400464b3e5.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/113018367/206297486-28b8186f-e9b7-48f8-9933-23f362eede2d.png">

**Additional context**
It was working fine few days back but suddenly today when I spawned a new notebook I cant use the Mosaic library anymore in databricks notebooks

**Comment by milos-colic** [comment]
@abhilshitsoni-tomtom Thank for raising the issue.
I cannot see the call for :
  import mosaic as mos
  mos.enable_mosaic(spark, dbutils)
in your example.
Could you please follow this example: https://github.com/databrickslabs/mosaic/blob/main/notebooks/examples/python/QuickstartNotebook.py

**Comment by abhilshitsoni-tomtom** [comment]
ooh I see. Totally missed that step. It works after adding that line. Thanks. Will close the ticket.
