### ISSUE TITLE
polyfill is depreceated

### ISSUE THREAD

**Issue by shanmugavel04** [databrickslabs/mosaic#305]
**Problem Description**
The [documentation](https://databrickslabs.github.io/mosaic/usage/grid-indexes.html), is outdated as in the #4 - **_**Compute the set of indices that fully covers each polygon in the right-hand dataframe**_**

```
from mosaic import polyfill

indexed_neighbourhoods = (
neighbourhoods
.select("*", polyfill("geometry", lit(resolution)).alias("ix_set"))
.drop("geometry")
)

indexed_neighbourhoods.show()
```

When:

polyfill [Deprecated]
polyfill(geom, resolution)
This is an alias for grid_polyfill

**Expected behavior**
Update the documentation with the latest API.

**Comment by edurdevic** [comment]
Good point! 
Thank you for reporting it @shanmugavel04!
