### ISSUE TITLE
Automatic SQL registration doesn't work

### ISSUE THREAD

**Issue by edobrynin-dodo** [databrickslabs/mosaic#317]
**Describe the bug**

I have mosaic 0.3.7.jar installed on my databricks cluster.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/98310581/226400647-7f6f557f-f1ea-4e17-a6b7-999d3a63161e.png">

I also put this jar into these locations:

- /databricks/jars
- /FileStore/mosaic/jars
- /FileStore/jars/mosaic/jars

<img width="546" alt="image" src="https://user-images.githubusercontent.com/98310581/226399409-08312c65-31c1-4d3e-914a-2afbcce4fdae.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/98310581/226399519-deab595f-1af7-461f-98fa-e836e4d0b074.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/98310581/226399627-bb6ea886-b110-4ca0-aee8-f06decb24524.png">

I put these spark configs to my cluster's "Advanced options" section:

- spark.sql.extensions com.databricks.labs.mosaic.sql.extensions.MosaicSQL
- spark.databricks.labs.mosaic.geometry.api JTS
- spark.databricks.labs.mosaic.index.system H3

<img width="898" alt="image" src="https://user-images.githubusercontent.com/98310581/226399265-5320aabf-8563-4634-8cc3-22fc7f94557c.png">

However, when I'm trying to check if Mosaic functions were registered:...

`spark.sql("""show functions""").where("startswith(function, 'st_')").display()`

...the result is zero unfortunately.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/98310581/226399080-26cc98db-8c6f-4d03-936c-4d8d8735d4ad.png">

**Expected behavior**
display() call shows functions from Mosaic library titled with "st_"

**Additional context**
- Databricks Runtime == 12.1 (includes Apache Spark 3.3.1, Scala 2.12), Photon OFF, Pricing tier == Standard

May I ask for help? 
Probably I do something wrong:(
Thank you in advance!

**Comment by bransonf** [comment]
I solved a similar issue by using
spark.sql.extensions com.databricks.labs.mosaic.sql.extensions.MosaicSQLDefault instead of
spark.sql.extensions com.databricks.labs.mosaic.sql.extensions.MosaicSQL in my spark config

Also mentioned this in #297

**Comment by edurdevic** [comment]
Hi @edobrynin-dodo, 
I see that you are installing the mosaic library from the Cluster UI. This procedure installs the library after the cluster is already started, after the SQL registration trigger.
In order to make it work, you need to install the Mosaic library via init script like described [here](https://databrickslabs.github.io/mosaic/usage/automatic-sql-registration.html).

Please let us know if that works.

**Comment by edobrynin-dodo** [comment]
Hi @edurdevic!

Got it, thank you.

I think the issue can be closed then.

May I create the PR to add this info in documentation?
For example in Apache Sedona they specifically write about it:

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/98310581/231515436-7ed89171-eec5-46e4-b9b0-84c142e3ad4a.png">
