### ISSUE TITLE
Incorrect python binding for `rst_georeference`

### ISSUE THREAD

**Issue by bnjmind** [databrickslabs/mosaic#322]
**Describe the bug**
Calling `mosaic.rst_georeference` throws a py4j error. Looking at the source code, I think the Python binding tries to invoke the wrong function (similar to the other bindings fixed in commit [6302973](https://github.com/databrickslabs/mosaic/commit/6302973dd4c9a469650f4a33e41120d2105b33fb)).

**To Reproduce**
1. Try to call `mosaic.rst_georeference`.

**Expected behavior**
No error should occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/16613223/226601913-9ad0f434-c8bc-4d3d-bac2-7e8ba2aa3ed7.png)

**Additional context**
Version 0.3.8

**Comment by edurdevic** [comment]
Indeed! Thank you for reporting this @bnjmind!
