### ISSUE TITLE
Support for rasters as `BinaryType` objects

### ISSUE THREAD

**Issue by bebitzko** [databrickslabs/mosaic#348]
**Is your feature request related to a problem? Please describe.**
Currently, in order to use the raster functionality, a path to the raster file must be supplied. This prevents use of these functions if the raster is already stored in a dataframe as BinaryType.

**Describe the solution you'd like**
I would like to be able to pass a column containing binary data that represents a raster to the raster functions, as an alternative to a column containing paths to the raster files themselves.
I'm only a novice with Scala, so I'm likely missing a gotcha here, but my gut feeling is that this change should be possible just by overloading [this method](https://github.com/databrickslabs/mosaic/blob/a5b72b737e32518fbe4d64179dec43a7ee9eba33/src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/Raster1ArgExpression.scala#L78-L86), such that it goes down an alternative path when a binary type is passed in instead of a string type.

**Describe alternatives you've considered**
In cases where the binary rasters already exist in a DataFrame as (such as exports from a PostGIS database using ST_AsGDALRaster), we could instead save the raster files directly to a filesystem.
In cases where the raster files exist inside of zip files, we could unzip them in the file system and reference their paths instead of loading and processing them as `BinaryType`.
To be honest, I don't like either of these alternatives, as they involve considerably more IO.

**Additional context**
We have numerous cases where raster files are bundled together in zip files for various reasons, and a few cases where we are ingesting exports from a PostGIS database. I would like to use mosaic's awesome functionality to convert them into H3 grids. In the second case, it would be very convenient to be able to operate directly on binary raster objects. In the first case, it's fairly easy to load the zip files as binary files, then use a UDF to extract the binary tif files we want, giving us a case similar to the second case, where we have rasters stored in a column in their binary form.

**Contributing to Mosaic**
Guidelines for contributing to Mosaic can be found in `CONTRIBUTING.md`.

**Comment by milos-colic** [comment]
Hi @bebitzko,

Thank you for the issue you submitted.
We have considered BinaryType for in-mem representation as well.
There are few complications with GDAL in MEM drivers that forced us to go via path route at the moment.
We have the in mem representation planned.
PostGIS API and behavior compatibility is on the road map and will come over next few versions.
I wanted to reasure you this something that is coming.

One thing I noticed that is tangential, you dont need to unzip any files when using GDAL enabled Mosaic since we use GDAL vsizip option to auto unzip files.

KR
Milos

**Comment by bebitzko** [comment]
Ah, I missed the vsizip option. I'll give that a go! Since the majority of my use cases are with zip files, this should work for the moment. And I definitely appreciate the rate at which new functionality is rolling out. Thank you!

**Comment by PranavDeshmane** [comment]
Was also was hoping for the functionality to read in BinaryType rasters already existing within a column in our Dataframe. Looking forward to it.

**Comment by bebitzko** [comment]
It looks like this issue is resolved by the new `rst_fromcontent()` method available in the 4.0 release. I was successfully able to load in some raster binaries, and use some raster functionality in Mosaic. Thank you @mjohns-databricks! 🙂

**Comment by mjohns-databricks** [comment]
Glad that worked out, docs updating very soon for the new function.
