### ISSUE TITLE
GDAL read is empty?

### ISSUE THREAD

**Issue by JimShady** [databrickslabs/mosaic#350]
![image](https://user-images.githubusercontent.com/2901470/233100843-001b44a4-7feb-4a9f-bc6e-e1d492e7f29e.png)

**Comment by JimShady** [comment]
But it' s fine just using gdal.

![image](https://user-images.githubusercontent.com/2901470/233101135-fd6ac9a5-7049-4515-8d87-705831493465.png)

**Comment by JimShady** [comment]
Similar using the raster_to_grid reader:

![image](https://user-images.githubusercontent.com/2901470/233102113-fe71a977-15ed-4578-9c0b-464c0c88f3a7.png)

**Comment by JimShady** [comment]
It is not publicly available unfortunately. Do you have a suggestion of a sample tif I could use instead to test if the issue persists?

**Comment by JimShady** [comment]
How about this file:

GHS_BUILT_V_E2020_GLOBE_R2022A_54009_1000_V1_0.tif

It gives me the same issue.

Available here:

https://ghsl.jrc.ec.europa.eu/download.php?ds=builtV

![image](https://user-images.githubusercontent.com/2901470/233120608-476155bc-63da-478f-93e3-c187e961d69a.png)

**Comment by JimShady** [comment]
Showing same error:

![image](https://user-images.githubusercontent.com/2901470/233121044-ab7eab93-9360-4c43-913d-59380731a21d.png)

**Comment by JimShady** [comment]
[sample_flood_file.zip](https://github.com/databrickslabs/mosaic/files/11274818/sample_flood_file.zip)

Here you go.

**Comment by JimShady** [comment]
![image](https://user-images.githubusercontent.com/2901470/233125189-c20d8ab4-1de3-4117-806e-1bee0bc66482.png)

**Comment by JimShady** [comment]
I presume at this point that I have something incorrectly configured, but I'm unsure what.

**Comment by milos-colic** [comment]
@JimShady thanks for sharing these, I will work on a fix today.
One thing you just raised is important and I will factor it in. There is an assumption on CRS being 4326 (which is not documented and too big of an assumption). I will add auto reprojection in case of other CRSs and if we have the ID inside the metadata we will use it to translate to 4326 for indexing purposes.

**Comment by milos-colic** [comment]
@JimShady I am not able to reproduce.
I have used the file you shared and I am able 
<img width="1253" alt="Screenshot 2023-04-20 at 10 08 42" src="https://user-images.githubusercontent.com/75583254/233317766-29086eed-94d9-4ff2-97f6-804912cf0710.png">
to read it both with vsizip and if I unzip it.

Could you confirm which Databricks Runtime you are using?

**Comment by JimShady** [comment]
![image](https://user-images.githubusercontent.com/2901470/233337926-5335531a-506f-42b9-87bb-369b36695e73.png)

**Comment by JimShady** [comment]
![image](https://user-images.githubusercontent.com/2901470/233338066-23da99aa-0036-479e-a436-d721ff4f1f79.png)

![image](https://user-images.githubusercontent.com/2901470/233338129-0d53cba7-2b4f-4ec3-85f4-90d1fd0efaf1.png)

**Comment by JimShady** [comment]
Let me know if you need anything else @milos-colic

**Comment by JimShady** [comment]
Changed my DBR to 11.3, but still getting the same result.

**Comment by JimShady** [comment]
![image](https://user-images.githubusercontent.com/2901470/233379418-48716cf6-361a-4d1f-b92d-61d3a6c3dcc3.png)

**Comment by JimShady** [comment]
Seems that it can see the file.

**Comment by milos-colic** [comment]
The issue is occurring due to documentation errors and it instructions aren't correct.

`driverName` option has to respect GDAL short driver names. For `.tif` files the correct driver name is `GTiff`.

Another issue that is occurring is the issue with `mos.read().format("raster_to_grid")` is the `fileExtension` option, this one requires a wildcard, `tif` wont work, but `*.tif` will work for tif files.

I will update the documentation with the correct call outs for the gotchas.
