### ISSUE TITLE
st_transform not working for dataframe created from geojson

### ISSUE THREAD

**Issue by mpiekarska** [databrickslabs/mosaic#351]
I am working with ONS Local Authority Boundary dataset: https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-december-2022-boundaries-uk-buc/ reading the data from dbfs. I want to perform st_transform from 27700 to 4326.

```
lad_df = (
    spark.read
        .format("ogr")
        .option("driverName", "GeoJSON")
        .option("asWKB", "false")
        .load(f"dbfs:/FileStore/shared_uploads/Local_Authority_Districts_December_2022_Boundaries_UK_BUC.geojson")
        .limit(1)

        # Add mosaic internal geom column 
        .withColumn('geom', mos.st_setsrid(mos.st_geomfromwkt('geom_0'), lit(27700)))
)

lad_df.select(mos.st_astext(mos.st_transform('geom', lit(4326)))).show(1, False)
```

The above does not work and returns: 
Py4JJavaError: An error occurred while calling o3434.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 101.0 failed 4 times, most recent failure: Lost task 0.3 in stage 101.0 (TID 302) (10.139.106.0 executor 0): java.lang.IllegalArgumentException: Could not parse Well-Known Text around position: 0

However when I take the same WKT geometry and create df like below, st_transform works.

```
df = (
    spark.createDataFrame([{'geom_0': 'POLYGON ((448973.593 536745.2773,448986.0254 536729.6745,453194.6 533938.4,453341.0836 533293.4014,453329.5704 533293.9857,451898.9208 534023.2414,452435.0 533448.25,452383.2079 533342.009199999,452174.11 533352.619999999,452036.2498 532630.2973,451738.0 532018.5,453270.8 529013.0,454454.98 528446.73,453471.9133 526822.3913,452499.69 526687.43,452243.5362 526335.188100001,451148.5004 525456.799000001,449537.399 526239.404999999,448090.9019 525608.795499999,445354.8031 526096.096000001,444216.0036 528004.899599999,443410.7002 527859.9011,443024.0975 526445.396,440052.7012 527819.7026,442604.5971 528543.395500001,442166.2979 529897.9977,443235.8966 532101.7969,442351.0037 533093.603,443974.9015 533135.301000001,445116.8012 535009.9045,444836.197 536055.495200001,447097.001 537152.0013,448290.1026 536324.7981,448973.593 536745.2773))'}])

   .withColumn('geom', mos.st_setsrid(mos.st_geomfromwkt('geom_0'), lit(27700)))
)

df.select(mos.st_astext(mos.st_transform('geom', lit(4326)))).show(1, False)
```

Cluster config: 
![image](https://user-images.githubusercontent.com/70478478/233401407-77bd8cba-abfc-44ca-8ff3-99e38d5aee67.png)

**Comment by milos-colic** [comment]
@mpiekarska Thank you for reporting the issue.
I have managed to reproduce and will work on identifying the core problem with spark.read.

The mosaic multi_read_ogr reader works without an issue:
<img width="902" alt="Screenshot 2023-04-21 at 19 13 03" src="https://user-images.githubusercontent.com/75583254/233706384-f59c5e40-39d7-497e-a52a-90a5fb5e34fc.png">


The workaround for spark.read is to write out the read dataframe into a table.
This will materialise the read columns and will sort out the issue.
<img width="942" alt="Screenshot 2023-04-21 at 19 09 49" src="https://user-images.githubusercontent.com/75583254/233705756-55630880-ba54-4f68-b5a8-370d220e15b9.png">


For context, something odd is happening in sparks optimizations and it seems the optimizer is not picking up the correct column hence the parsing fails. But when we write the table out that prevents that issue.

**Comment by r3stl355** [comment]
I also looked into this and noticed that despite `lad_df.printSchema` showing the correct schema, `lad_df.select("geom_0")` selects the first column value.

Another alternative/temporary fix is dropping to RDD and back, which sorts things out, e.g. 

```
lad_df = (
    spark.read
        .format("ogr")
        .option("driverName", "GeoJSON")
        .option("asWKB", "false")
        .load(f"dbfs:/FileStore/shared_uploads/Local_Authority_Districts_December_2022_Boundaries_UK_BUC.geojson")
        .limit(1)
)

df = (lad_df
              .rdd
              .toDF(lad_df.columns)
              .withColumn('geom', mos.st_setsrid(mos.st_geomfromwkt('geom_0'), F.lit(27700)))
              .select(mos.st_astext(mos.st_transform('geom', F.lit(4326)))).show(1, False)
        )
```

**Comment by mpiekarska** [comment]
@milos-colic @r3stl355 
Thank you both for looking into the issue and for sharing you insights and suggestions. For now I used mosaic multi_read_ogr reader as suggested by @milos-colic and read data successfully. I am looking forward to spark.read.format fix.
