### ISSUE TITLE
incomplete coverage from grid_geometrykring and grid_tessellate

### ISSUE THREAD

**Issue by Therealchainman** [databrickslabs/mosaic#360]
This bug affects the output of these spatial grid indexing functions `grid_geometrykringexplode`, `grid_tessellateexplode`,  `grid_geometrykring`, and `grid_tessellate`.

setup in databricks cluster
```py
%pip install databricks-mosaic==0.3.9 apache-sedona==1.4.0
import pyspark.sql.functions as F
from pyspark.databricks.sql.functions import *
import mosaic as mos
mos.enable_mosaic(spark, dbutils)
from sedona.register.geo_registrator import SedonaRegistrator
SedonaRegistrator.registerAll(spark) 
from pyspark.databricks.sql.functions import *
```

To visualize each one we are running in a cell.
```py
%%mosaic_kepler
line_segment_cover_sdf h3_13 h3 100_000
```

I'm going to paste a few examples for how to reproduce the error, the expected behavior with all of these is that the resolution 13 h3 cell would cover the entire line segment.  Originally it was discovered with a resolution 12 h3 cell and we found switching to different resolution fixed those line strings, but it was soon discovered that switching to resolution 13 h3 cells just creates the issue with different line strings.  We are not sure what could be causing this bug. 

```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-83.488541 42.220045, -83.4924813 42.2198315)'}])
    .withColumn('h3_13', mos.grid_geometrykringexplode('line_segment', F.lit(13), F.lit(2)))
)
```
<img width="507" alt="kring1" src="https://user-images.githubusercontent.com/47466952/234801260-af4545f9-39fd-4e17-a735-bc6ec0e6ba5f.PNG">

What happens if I reverse the line string
```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-83.4924813 42.2198315, -83.488541 42.220045)'}])
    .withColumn('h3_13', mos.grid_geometrykringexplode('line_segment', F.lit(13), F.lit(2)))
)
```
<img width="200" alt="kring2" src="https://user-images.githubusercontent.com/47466952/234802507-ac8a2b9c-f898-4016-a234-50b07a1500cd.PNG">

What happens if I go to a resolution 12 h3 cells.  It appears to not be dropping the h3 cells.  But we already know other line strings have the same issue with resolution 12 h3 cells. 
```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-83.4924813 42.2198315, -83.488541 42.220045)'}])
    .withColumn('h3_13', mos.grid_geometrykringexplode('line_segment', F.lit(12), F.lit(2)))
)
```
<img width="315" alt="kring3" src="https://user-images.githubusercontent.com/47466952/234803099-821e5c1d-9889-43f5-8bae-bc3229973713.PNG">

```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-86.4012318 41.671962, -86.4045068 41.6719684)'}])
    .withColumn('h3_13', mos.grid_geometrykringexplode('line_segment', F.lit(13), F.lit(2)))
)
```
<img width="492" alt="kring4" src="https://user-images.githubusercontent.com/47466952/234805179-623d5e9a-979a-4c19-ae0a-5f45539f2142.PNG">

We found for a few of the line strings if you just reverse the points it covers the entire line string. 

```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-86.4045068 41.6719684, -86.4012318 41.671962)'}])
    .withColumn('h3_13', mos.grid_geometrykringexplode('line_segment', F.lit(13), F.lit(2)))
)
```
<img width="128" alt="kring5" src="https://user-images.githubusercontent.com/47466952/234805505-9caf5e78-5b85-4fd2-a575-ca7010b11d03.PNG">

```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-85.0040681 42.2975028, -85.0073029 42.2975266)'}])
    .withColumn('h3_13', mos.grid_geometrykringexplode('line_segment', F.lit(13), F.lit(2)))
)
```
<img width="195" alt="kring6" src="https://user-images.githubusercontent.com/47466952/234806115-b0eb0bfd-c4e1-4de7-8b68-24aa7c847a06.PNG">

What happens if we try `grid_tessellateexplode` instead? 

```py
line_segment_cover_sdf = (
    spark.createDataFrame([{'line_segment': 'LINESTRING (-85.0040681 42.2975028, -85.0073029 42.2975266)'}])
    .withColumn('h3_13', mos.grid_tessellateexplode('line_segment', F.lit(13)))
    .withColumn('h3_13', F.col('h3_13').index_id)
)
```
<img width="460" alt="tessellate1" src="https://user-images.githubusercontent.com/47466952/234807314-f77df4c0-4ab8-48bb-8555-b3585643c1c5.PNG">

Expected behavior

It should cover the entire line string with h3 cells.

**Comment by r3stl355** [comment]
I'll try to solve this over the coming weekend

**Comment by edurdevic** [comment]
Thank you @Therealchainman for reporting this and thank you @r3stl355 for looking into it! At first glance I suspect this might be related to the icosahedron projection distortion from #229 (but might also be a more trivial bug).
You can expand on the unit test `lineDecomposeFirstPointOnBoundary` to check for this scenario @r3stl355

**Comment by r3stl355** [comment]
I confirmed that this is a bug, PR with a fix is on it's way

**Comment by Therealchainman** [comment]
Thanks for the quick fix!
