### ISSUE TITLE
DBR 12.2 LTS not supported by Mosaic 0.3.10 ?

### ISSUE THREAD

**Issue by JimShady** [databrickslabs/mosaic#369]
The latest release of mosaic (0.3.10) is warning that my Databricks runtime is not supported (12.2 LTS). I think that this is probably an error/bug?

![image](https://user-images.githubusercontent.com/2901470/237048136-b1ab695b-5c94-47d6-8c25-144dbadc20ee.png)

![image](https://user-images.githubusercontent.com/2901470/237048199-37b5800d-f8fa-44f8-8428-11524c2e333b.png)

**Comment by edurdevic** [comment]
Yes, this is a bug. We are working on fixing it.
Thank you for reporting.
