### ISSUE TITLE
Supporting non DBR environments

### ISSUE THREAD

**Issue by abhijit-pawar** [databrickslabs/mosaic#376]
**Is your feature request related to a problem? Please describe.**
It would be good for Mosaic to support Non Databricks runtimes like regular EMR / Dataproc clusters.

**Describe the solution you'd like**
Ideally the base dependency on some of the databricks libraries should be updated so that Mosaic can run on its own

**Describe alternatives you've considered**
The only alternative I have is to re-do what Mosaic is doing using H3 Core and JTS libraries which would defeat the purpose.

**Comment by r3stl355** [comment]
Hi, as far as I know, Mosaic does not require DBR to run. For example, I happily build and run it on my Mac (and also in a Docker not built from DBR). I have not tried the packaged version, though I don't think it requires DBR

**Comment by abhijit-pawar** [comment]
Thanks.  I have added the mosaic-jar-with-dependencies in the class path in a spark-shell on a data-rod cluster and it's working. Will check with a Spark Scala application.

**Comment by abhijit-pawar** [comment]
With Spark Scala application I was able to run the code from notebook to process NYC Taxi data into a Google dataproc cluster.
