### ISSUE TITLE
`grid_pointascellid` fails with a Java type error when run on an already instantiated point

### ISSUE THREAD

**Issue by tigerhawkvok** [databrickslabs/mosaic#383]
For a Spark table `df`, I create a `Point`. My specific example is in a DLT pipeline on Databricks/AWS:

```python
import dlt
import mosaic as mos
from pyspark.sql import functions as F


spark.conf.set(
    "spark.databricks.mosaic.geometry.api",
    "ESRI"
)
mos.enable_mosaic(spark, dbutils)


@dlt.table(
    comment= "addresses",
    partition_cols= ["countryCode", "region"],
    table_properties= {"pipelines.autoOptimize.zOrderCols": "addressID"},
    temporary= True
)
def address():
    # [ stuff]
    out = df.withColumn("point", mos.st_setsrid(mos.st_point(F.col("lng"), F.col("lat")), F.lit(4326))) \
            .filter(mos.st_isvalid(F.col("point")))
    return out
```

And in a different descendant table, I want to add an h3 index:

```python
from typing import cast, Final
from pyspark.sql.dataframe import DataFrame as DataFramePS
USE_SRID:Final[int] = 3857
@dlt.table(
    comment= "Mosaic Geometries",
    partition_cols= ["countryCode", "region"],
    table_properties= {"pipelines.autoOptimize.zOrderCols": "h3Index"},
)
def geometryAddress():
    withTransformed = cast(DataFramePS, dlt.read("address")).withColumn("coordGeom", mos.st_transform(F.col("point"), F.lit(USE_SRID)))
    resolution = 10 # In real life, I use a try-except statement to attempt to get it with get_optimal_resolution
    withTransformed = withTransformed.withColumn("bestH3Resolution", F.lit(resolution))
    withIndex = withTransformed.withColumn("h3Index", mos.grid_pointascellid(F.col("point"), F.col("bestH3Resolution"))) # Fails
    # withIndex = withTransformed.withColumn("h3Index", mos.grid_pointascellid(mos.st_setsrid(mos.st_point(F.col("lng"), F.col("lat")), F.lit(4326)), F.col("bestH3Resolution"))) # Succeeds
    return withIndex
```

Reusing the point fails with an error similar to:

> `org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 16051.0 failed 4 times, most recent failure: Lost task 4.3 in stage 16051.0 (TID 136056) (10.193.102.205 executor 75): java.lang.Error: StructType(StructField(type_id,IntegerType,true),StructField(srid,IntegerType,true),StructField(boundary,ArrayType(ArrayType(ArrayType(DoubleType,true),true),true),true),StructField(holes,ArrayType(ArrayType(ArrayType(ArrayType(DoubleType,true),true),true),true),true)) not supported.`

but instancing one in-place works fine.

**Expected behavior**

An existing point should be able to be reused; failing that, the error should bubble up to Python and be helpful. The java lang error is obscure and difficult to trace.

**Additional context**

I've only attempted this in a DLT pipeline.

**Comment by r3stl355** [comment]
Hi @tigerhawkvok, do you have any specific point coordinates I can test this with or will any lon/lat show this behavior?

**Comment by tigerhawkvok** [comment]
As far as I know any point will do it

**Comment by r3stl355** [comment]
Hi, this could be a bug (e.g. maybe something isn't working as expected when saved & loaded via a table ). There seems to be no issue when everything is done in memory - I mean both ways of obtaining an index work, here is an in-memory version of your code:
```
        df = spark.createDataFrame([{'lng': 10.1, 'lat': 20.2}])
        with_point = (df
            .withColumn("point", mos.st_setsrid(mos.st_point(F.col("lng"), F.col("lat")), F.lit(4326))) \
            .filter(mos.st_isvalid(F.col("point")))
        )
        with_index = (with_point
            .withColumn("bestH3Resolution", F.lit(10))
            .withColumn("h3Index", mos.grid_pointascellid(F.col("point"), F.col("bestH3Resolution")))
            .withColumn("h3Index2", mos.grid_pointascellid(mos.st_setsrid(mos.st_point(F.col("lng"), F.col("lat")), F.lit(4326)), F.col("bestH3Resolution")))
        )
        with_index.show()
```

I'll try with a table and maybe with DLT after

**Comment by r3stl355** [comment]
It looks like a geometry saved to a table fails to be parsed back into a geometry. I'll keep investigating further, but a possible workaround could be converting the geometry to one of the well-known types (e.g. WKB as in the example below) before persisting.
1. In you `address` table:
```
out = ....
          .withColumn("point_wkb", mos.st_aswkb(F.col("point")))
```
2.And in the other table:
```
withIndex = withTransformed
          .withColumn("h3Index", mos.grid_pointascellid(mos.api.st_geomfromwkb(F.col("point_wkb")), F.col("bestH3Resolution")))
```

**Comment by tigerhawkvok** [comment]
Good to be aware of the workaround. Interestingly, the parse-back-to-geometry seems to be particular to the `pointascellid` function -- I later use `mos.st_distance()` on the saved geometry and that works fine. 

Perhaps the parse logic isn't being reused?

**Comment by r3stl355** [comment]
The error is thrown here which looks like a place to be used but most, if not all the parsing code. I'll also check why `st_distance` is working but `pointascellid` does not:
 https://github.com/databrickslabs/mosaic/blob/bb49756b0bc22beb2a23f64297e1b444b25be2da/src/main/scala/com/databricks/labs/mosaic/core/geometry/api/GeometryAPI.scala#L50

**Comment by r3stl355** [comment]
I have a fix that works, will file a PR soon. (however, It won't improve the error message if an attempt is made to parse an invalid structure - that will still be a Java error)
