### ISSUE TITLE
Using st_buffer doesn't return a Polygon geometry

### ISSUE THREAD

**Issue by keval-ll** [databrickslabs/mosaic#387]
I am expecting to create a buffer around `point` geometry that would be of `Polygon` type. For example, I run the following code to obtain the geometries. 

```

df = spark.createDataFrame([
    (37.775, -122.418),
    (40.714, -74.006),
    (41.007, 28.613),
], ["lat", "long"])


df1 = df.withColumn("point_geom", st_point("lat", "lng"))
df1.select('point_geom').show(5)

--------------------+
|          point_geom|
+--------------------+
|{1, 0, [[[32.4374...|
|{1, 0, [[[32.4374...|
|{1, 0, [[[32.4374...|
|{1, 0, [[[32.4374...|
|{1, 0, [[[32.4374...|


df2 = df1.withColumn("geom_buffer", st_buffer("point_geom", lit(.2)))
df2.select('geom_buffer').show(5)

--------------------+
|         geom_buffer|
+--------------------+
|{5, 4326, [[[32.6...|
|{5, 4326, [[[32.6...|
|{5, 4326, [[[32.6...|
|{5, 4326, [[[32.6...|
|{5, 4326, [[[32.6...|
+--------------------+

```

1. Why are these not `Point` or of `Polygon` type? How do we convert them to geometry type?
2. What is the unit of `radius` in `st_buffer`? It is not clear from the docs. 
3. What do the numbers in `{1,  0} {5, 4326}` represent?  

https://databrickslabs.github.io/mosaic/api/spatial-functions.html

**Comment by r3stl355** [comment]
Hi, 
1. the type is Polygon, you can convert to WKT to see details, e.g. add  a WKT column and display 
```df2 = (df1
            .withColumn("geom_buffer", mos.st_buffer("point_geom", F.lit(0)))
            .withColumn("wkt", mos.st_aswkt("geom_buffer"))
        )
```
2. The unit is the same as lon and lat. Try using `lit(0)` and you'll get back your Point
3. Those numbers represent an internal representation of the geometry used in Mosaic - type_id, SRID and so on 

HTH

**Comment by keval-ll** [comment]
Got it. makes sense to use `st_aswkt` to obtain the polygon geometries. 

Is there a way to check the units of `lat, lon` in spark dataframe? With `geopandas`, I use the `.crs` method.

**Comment by r3stl355** [comment]
The units are specific to the Spatial Reference System of the geometry. In your case (and by default) you are using WGS 84 (which has SRID 4326, the second number you asked about earlier) which uses degrees as units. You'll get the same info using .crs on geopandas
