### ISSUE TITLE
SSL Error on https://databrickslabs.github.io

### ISSUE THREAD

**Issue by bmoregeo** [databrickslabs/mosaic#392]
**Describe the bug**
When I go to the documentation page, I am greeted with an SSL error. When I attempt to use the page in http mode, my router says there is malware at the URI. It feels like something is terribly wrong with the documentation page.

https://databrickslabs.github.io/mosaic/

Secure Connection Failed

An error occurred during a connection to databrickslabs.github.io. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…

**To Reproduce**
1. Go https://databrickslabs.github.io/mosaic/ in a web browser

**Expected behavior**
Should be able to see documentation

**Screenshots**

**Additional context**

**Comment by milos-colic** [comment]
@bmoregeo Thank you for reporting the issue.
I am not able to reproduce it on my end.
I inspected the certificate (which is for *.github.io so not mosaic specific) and it is valid until 2024.
Can you clear cookies and retry?
Can you make sure you arent on a VPN?
Can you try another browser?

**Comment by bmoregeo** [comment]
Strange, it works from my phone. Not sure why that page has been singled out by my router to block traffic. Thanks!
