### ISSUE TITLE
Internal error: com.databricks.rpc.RPCResponseTooLarge, when attempting to use mosaic's st_intersects

### ISSUE THREAD

**Issue by keval-ll** [databrickslabs/mosaic#409]
I get an exception when attempting to run the following line of code, which filters a spark DataFrame based on the geometry.

```
 df_tx = df_zip.filter(st_intersects(st_aswkt("zip_code_geom"), tx_poly))

 df_tx.show()
```

where,  `tx_poly` is,

`tx_poly = shapely.wkt.dumps(tx_poly2)`

Exception: 

`Internal error. Attach your notebook to a different compute or restart the current compute.
  com.databricks.rpc.RPCResponseTooLarge: rpc response (of 20982872 bytes) exceeds limit of 20971520 bytes
  at com.databricks.rpc.Jetty9Client$$anon$1.onContent(Jetty9Client.scala:657)
  at shaded.v9_4.org.eclipse.jetty.client.api.Response$Listener.onContent(Response.java:294) `

**Comment by milos-colic** [comment]
@keval-ll This is not a mosaic issue per se, this is due to having too much data to display using show.
One of your columns is probably containing a very large WKT/WKB.

Can you call .show() on df_zip and tx_poly to verify that works?

**Comment by keval-ll** [comment]
@milos-colic `df_zip.show()` works, `tx_poly` is of type `str`. Running `print(tx_poly)` gives, 

` 'POLYGON ((-97.3945020000000028 25.8371640000000014, -97.3941229999999933 25.8371920000000017, -97.3937099999999987 25.8372819999999983, -97.3933660000000003 25.8373950000000008, -97.3929569999999956 25.8376179999999991, -97.3925550000000015 25.8378990000000002......)) `

**Comment by keval-ll** [comment]
`st_intersects` accepts `geom1` and `geom2` of column type. 

So, i tried to save the the polygon as: 

`df_tx = spark.createDataFrame([{'wkt': st_aswkt(tx_poly)}])` and then attempted to run,

`df_tx1 = df_zip.filter(st_intersects(df_zip.zip_code_geom, df_tx.wkt))` 

However, i get an Exception: 

```
AnalysisException: Resolved attribute(s) wkt#2386 missing from postal_code#1869,zip_name#1870,zip_code_geom#1871,avg_score#1872,h3_hex_id_lst#1879 in operator !Filter st_intersects(zip_code_geom#1871, wkt#2386, MosaicExpressionConfig(Map(spark.databricks.labs.mosaic.geometry.api -> ESRI, spark.databricks.labs.mosaic.index.system -> H3, spark.databricks.labs.mosaic.raster.api -> GDAL, spark.databricks.labs.mosaic.raster.checkpoint -> dbfs:/tmp/mosaic/raster/checkpoint))).;
!Filter st_intersects(zip_code_geom#1871, wkt#2386, MosaicExpressionConfig(Map(spark.databricks.labs.mosaic.geometry.api -> ESRI, spark.databricks.labs.mosaic.index.system -> H3, spark.databricks.labs.mosaic.raster.api -> GDAL, spark.databricks.labs.mosaic.raster.checkpoint -> dbfs:/tmp/mosaic/raster/checkpoint)))
+- Project [postal_code#1869, zip_name#1870, zip_code_geom#1871, avg_score#1872, h3_hex_id#1873 AS h3_hex_id_lst#1879]
   +- SubqueryAlias .....
      +- Relation i....[postal_code#1869,zip_name#1870,zip_code_geom#1871,avg_score#1872,h3_hex_id#1873] parquet
```

**Comment by keval-ll** [comment]
@milos-colic any suggestions on how to get this work?

**Comment by milos-colic** [comment]
@keval-ll 

Apologies for the delayed reply.
Based on what I am seeing in the error message this isnt a Mosaic issue.

You cant use resolved attributed cross-dataframes.
IE you cant use df_tx.wkt in df_zip.filter.

Also from the code I cannot say what the schema is of df_zip.
Based on the error it seems to only have "postal_code", "zip_name", "zip_code_geom", "avg_score" and "h3_hex_id_lst", so that is why filter fails, there is no wkt column in df_zip.

**Comment by keval-ll** [comment]
@milos-colic 

Right. There's no `wkt` column in `df_zip`. `wkt` column is in `df_tx`.  The geometry column in `df_zip` is `zip_code_geom`. I am trying to do a spatial join on `df_zip` and `wkt` column in `df_tx`.  

So, my spatial join code looks something like this:

`df_tx1 = df_zip.filter(st_intersects(df_zip.zip_code_geom, df_tx.wkt))` 

The schema of `df_zip`:

```
root

 |-- postal_code: string (nullable = true)
 |-- zip_name: string (nullable = true)
 |-- zip_code_geom: string (nullable = true)
 |-- avg_score: double (nullable = true)
 |-- h3_hex_id_lst: array (nullable = true)
 |    |-- element: long (containsNull = true)
```

**Comment by milos-colic** [comment]
@keval-ll 

It is not possible to do a spatial join via filter function.

You need to use a join operator.

You have an example of how to do this here:
https://databrickslabs.github.io/mosaic/usage/quickstart.html#Mosaic-spatial-join-optimizations

**Comment by keval-ll** [comment]
@milos-colic 

Thanks for sharing. 

I see there are examples on PIP and general info on how to efficiently implement spatial joins in PySpark. However, I am trying to do a polygon-polygon intersect vs a Point-in-Polygon join.

Are there any examples of Polygon intersection that you can share?
