### ISSUE TITLE
Vector loading from CSV

### ISSUE THREAD

**Issue by JimShady** [databrickslabs/mosaic#411]
Say I have a CSV file called 'polygons.csv' and inside it, there is a column called 'wkt' which contains the WKT representation of my polygons. Can I read it with Mosaic?

I think I'll need the below snipped but I'm unsure how to do it properly.

Thanks!

```
df = spark.read.format("ogr")\
    .option("driverName", "CSV")\
    .option("layerName", "polygons")\
    .option("asWKB", "false")\
    .load("file:///tmp/polygons.csv")
df.show()
```

**Comment by mjohns-databricks** [comment]
@JimShady you can the CSV with standard spark reader, e.g. `spark.read.format("csv")[.option(...)].load(...)`. Then you can call various ST_ functions on the dataframe, see [docs](https://databrickslabs.github.io/mosaic/api/api.html). WKT is just a string and Mosaic can work directly against it.

**Comment by JimShady** [comment]
Thanks @mjohns-databricks
