### ISSUE TITLE
`setup_gdal` breaks due to lack of `shared_objects_path` parameter

### ISSUE THREAD

**Issue by tauhlim** [databrickslabs/mosaic#445]
**Describe the bug**
`setup_gdal` fails with error as `shared_objects_path` is no longer an accepted function parameter.

**To Reproduce**
1. Install `databricks-mosaic`
1. Try to setup GDAL using `mos.setup_gdal(spark)`
1. See error

**Expected behavior**
Either function allows you to specify `shared_objects_path`, or shouldn't reference the variable.

**Additional context**
Issue seems to happen due to this commit: https://github.com/databrickslabs/mosaic/commit/509cf318e62a01f938d2a0f7cb89f8a866d6b948

**Comment by milos-colic** [comment]
@tauhlim Thank you for reporting this.
We have released mosaic v0.3.12 last week and changed the way init scripts work. We will sort out the setup_gdal function in the next release. However setup_gdal is no longer needed, nor are the .so (shared objects).
You can use our new init_script provided here instead: https://github.com/databrickslabs/mosaic/blob/main/modules/python/gdal_package/databricks-mosaic-gdal/resources/scripts/mosaic-gdal-3.4.3-filetree-init.sh

Alternatively, you can fix your pip isntall to 0.3.11 of mosaic and that will make the code run as before.
