### ISSUE TITLE
Issue with reading raster files larger than 2 gb (> 2gb)

### ISSUE THREAD

**Issue by Apoorv2308** [databrickslabs/mosaic#467]
*Unable to read binary files greater than 2 GB**
I have installed databricks-mosaic. When I try to read a raster files with size greater than 2 GB; I get the error. The read is done using spark.read.format('gdal').option('extensions','tif').load('filename') command.

**To Reproduce**
1. Spark read a larger than 2 GB raster file.
2. Try display(dataframe)
3. See error

**Expected behavior**
The expectation is to be able to read the large binary file.

**Screenshots**
I have attached the screenshot of the error message.

**Additional context**
I had a call with Milos and he mentioned that its a small fix. There is a need to disable a check which errors out while reading larger than 2 GB file.
<img width="1311" alt="Larger Raster File Error" src="https://github.com/databrickslabs/mosaic/assets/152415544/c684054b-71b5-41f6-9a73-31b115fbb268">

**Comment by Apoorv2308** [comment]
Hi Afsana, team,

May I know when is the tentative date for the upcoming release?

Kind regards,
Apoorv

**Comment by mjohns-databricks** [comment]
[Mosaic 0.4.1](https://github.com/databrickslabs/mosaic/releases/tag/v_0.4.1) is released. You now have the option to use paths instead of just in memory for tiles, to include checkpointing with new `rst_maketiles` function, see docs [PR](https://github.com/databrickslabs/mosaic/pull/549) for more.
