### ISSUE TITLE
Documentation Link on how to use Mosaic-gdal UDFs to perform arbitrary algebra

### ISSUE THREAD

**Issue by Apoorv2308** [databrickslabs/mosaic#470]
**Describe the bug**
Documentation is missing on how to use databricks-mosaic gdal UDFs to perform arbitrary algebra

**To Reproduce**
There is currnently no link to documentation online to help perform algebraic operations using UDFs

**Comment by abafzal** [comment]
https://databrickslabs.github.io/mosaic/api/raster-functions.html#rst-mapalgebra

**Comment by mjohns-databricks** [comment]
See [RST_MapAlgebra](https://databrickslabs.github.io/mosaic/api/raster-functions.html#rst-mapalgebra) function; also see [RST_DerivedBand](https://databrickslabs.github.io/mosaic/api/raster-functions.html#rst-derivedband) and new in [Mosaic 0.4.1](https://github.com/databrickslabs/mosaic/releases/tag/v_0.4.1) RST_Convolve and RST_Filter, more in Docs [PR](https://github.com/databrickslabs/mosaic/pull/549). We intend to document examples of GDAL UDFs also, stay tuned.
