### ISSUE TITLE
support additional configuration options ST_Buffer

### ISSUE THREAD

**Issue by rickamsterdam** [databrickslabs/mosaic#486]
**Is your feature request related to a problem? Please describe.**
I'd like to be able configure `ST_Buffer` behaviour.

**Describe the solution you'd like**
I'd like to use the full set of configuration options provided by JTS: https://github.com/locationtech/jts/blob/9fd9c487f6c57ee9465bcaaaa301c8ee689cf2e3/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L1258-L1261

**Contributing to Mosaic**
If it's as simple as forwarding some parameters, I'd be happy to contribute a fix for this given some pointers.
Or is this not supported by design because these configuration options are not supported by ESRI?

**Comment by milos-colic** [comment]
@rickamsterdam
We can add this in versions 0.4.x+ where we will deprecated ESRI APIs and use only JTS.
Once that is sorted (~1-2weeks) we can add a PR for implementing changes you propose above.

**Comment by danielsparing** [comment]
Do we already have another example with a mosaic function that can be called with multiple different numbers of arguments? (à la buffer(a,b) and buffer(a,b,c) )
