### ISSUE TITLE
Bump h3 dependency for simplified local development

### ISSUE THREAD

**Issue by landlord-matt** [databrickslabs/mosaic#533]
**Describe the bug**
When trying install Mosaic on Ubuntu 22.04 with Python 3.10.12, the installation fails because of the [h3==3.7.0 dependency here](https://github.com/databrickslabs/mosaic/blob/a7ab70b57a6a7abf2fb566bd71cdddd57fc640ad/python/setup.cfg#L22). It is however possible to install h3==3.7.4 (likely because of [the effort to support more platforms](https://github.com/uber/h3-py/blob/master/CHANGELOG.md#374---2022-04-14)). Can you bump the dependency on h3?

**To Reproduce**
1. `pip3 install databricks-mosaic==0.4.0`

```
Building wheels for collected packages: h3, pyspark
Building wheel for h3 (pyproject.toml) ... error
[...]
scikit-build could not get a working generator for your system. Aborting build.
      
                      Building Linux wheels for Python 3.10 requires a compiler (e.g gcc).
      But scikit-build does *NOT* know how to install it on ubuntu
```

**Expected behavior**
Mosaic should be installed without additional steps

**Comment by mjohns-databricks** [comment]
DBR 13.3 (Ubuntu 22.04 version supported by Mosaic 0.4 series) supports H3 3.7.0 [[1](https://docs.databricks.com/en/release-notes/runtime/13.3lts.html)]. Can you explain more of what is not working when you run in DBR 13.3?

**Comment by landlord-matt** [comment]
SAD! I didn't think of that :(

It seems even the brand new [DBR 14.3](https://docs.databricks.com/en/release-notes/runtime/14.3lts.html) is only using h3 3.7.3. Technically the Java library, but [it seems it follows the Java version](https://github.com/uber/h3-py/blob/master/CHANGELOG.md#versioning).

> Because H3-Py is versioned in lockstep with the H3 core library, please avoid adding features or APIs which do not map onto the [H3 core API](https://uber.github.io/h3/#/documentation/api-reference/).

It works when it runs in DBR, but in this case, I was mostly interested in getting the syntax checks in my local IDE by having the Mosaic Python library installed. If it were no reason in particular for locking such an outdated version, it would make sense to bump it. Now that we know it reflects the DBR version the Mosaic library target, it doesn't.

I guess the options are to figure how to install it in the custom way or simply live with it not working.
