### ISSUE TITLE
GDAL error with mos.read ?

### ISSUE THREAD

**Issue by JimShady** [databrickslabs/mosaic#548]
I seem to have set-up Mosaic correctly. ![image](https://github.com/databrickslabs/mosaic/assets/2901470/1c0bee15-a7af-483b-a810-375889fca54c)

I've tested a few functions:

![image](https://github.com/databrickslabs/mosaic/assets/2901470/356f00f5-2360-44dc-b4a0-0a0fff148c60)

But when I try to convert a TIF to a H3 grid, it fails with some sort of link error that I don't understand:

![image](https://github.com/databrickslabs/mosaic/assets/2901470/87538d38-1e4c-4774-afa0-d66bd684f3db)

**Comment by sllynn** [comment]
Hi Jim. Surprised to see GDAL version 3.8.4 there, if all has gone to plan it should show 3.4.1. To get the raster capabilities of Mosaic to work, GDAL must be installed by the init script that's produced when running `setup_gdal()` (see our guidance [↗︎](https://databrickslabs.github.io/mosaic/usage/install-gdal.html#configure-the-init-script)) and you must be running the appropriate version of the Databricks runtime for the version of Mosaic that you're using (i.e. for Mosaic 0.4.1, that's DBR 13.3 LTS).

Can you make sure all of those things are configured correctly and if you have some other script that runs at cluster start or any other way of installing a later version of GDAL, please disable it to avoid version clash.

**Comment by JimShady** [comment]
Hi @sllynn  . Thanks for the help. I did have a seperate init script which did GDAL, so I've removed that now, and am only using the one that is generated by the Mosaic package. I'm not getting a separate error however.

![image](https://github.com/databrickslabs/mosaic/assets/2901470/ab10a289-269a-4b85-a2bb-a8888c8d76c7)

**Comment by JimShady** [comment]
I think that this might be because I made changes to my spark_config actually. I was testing the apache-sedona GIS library and it was required. I'll change it back and see if that helps ....

**Comment by JimShady** [comment]
Yes, it was. Things are working as expected now. Thanks.
