### ISSUE TITLE
Can't import MosaicAnalyzer

### ISSUE THREAD

**Issue by tony189** [databrickslabs/mosaic#551]
I'm not able to import or use MosaicAnalyzer, it is now supose to work wyth pyspark dataframes and MosaicFrames being deprecated. However I'm not able to import it or use it. 

I wasn't able to find anything in the docs

I wasn't able to import sql folder which contains the class...

Does anyone being able to use it?

Is there other way to optimize the resolution grid param?

Thank you in advance

**Comment by sllynn** [comment]
Hi Tony.

You're quite right it needs documenting. I think perhaps we stripped away all of the docs relating to MosaicFrames and didn't retain the Analyzer component anywhere. An oversight on our part.

If you take a look at the python package source [here](https://github.com/databrickslabs/mosaic/blob/main/python/mosaic/models/analyzer/analyzer.py) that should give you an idea of how it is designed to work. Import `MosaicAnalyzer` from `mosaic.models.analyzer`, initialise it with your dataframe and then call `get_optimal_resolution` passing the name of your geometry column.

HTH. Let us know how you get on.

**Comment by tony189** [comment]
I wasn't able to solve it. I understood that analyzer needs an array as imput. This is my code 

# Define a UDF that converts a column into an array
def to_array(col):
    return col.toArray()

# Register the UDF
array_udf = udf(to_array, ArrayType(StringType()))

# Apply the UDF to the 'geom' column
geom = limitesMunicipios.withColumn('geom_array', array_udf(limitesMunicipios['MULTIPOLYGON']))

try:
    analizador = MosaicAnalyzer(geom)

    resolution = analizador.get_optimal_resolution('geom_array', 1)
    display(resolution) 
except Exception as e:

    original_exception = sys.exc_info()[0]
    print(f"Original Exception: {original_exception}")

The error is
Original Exception: <class 'py4j.protocol.Py4JJavaError'>

**Comment by sllynn** [comment]
Sorry, I should have explained better. The analyser takes a dataframe with a geometry column as an input. If I assume that your `limitesMunicipios` is a dataframe with a column `geom_0` for feature geometries (in WKT, WKB, GeoJSON encoding) then your code would look like the following:

``` python
import mosaic as mos
from mosaic.models.analyzer import MosaicAnalyzer
mos.enable_mosaic(spark, dbutils)

limitesMunicipios = spark.read... # read from a csv, shapefile, whatever

analizador = MosaicAnalyzer(limitesMunicipios)
analizador.get_optimal_resolution("geom_0", sample=1.0)
```

`sample` in this context is the proportion of rows to consider for analysis. Very large datasets can be small to analyse but for e.g. Spanish municipalities probably 100% of rows is fine.

**Comment by tony189** [comment]
Works great!

Thank you for your quick response.

**Comment by sllynn** [comment]
con gusto 👍
