### ISSUE TITLE
Calling `rst_mapalgebra` as documented results in TypeError

### ISSUE THREAD

**Issue by ratteripenta** [databrickslabs/mosaic#571]
**Describe the bug**

Calling `rst_mapalgebra` with a proper tile (calling other `rst_*` functions works) results in TypeError. The error stems from how the `pyspark.sql.functions._to_java_column` is utilized in the [mapalgebra Python API implementation](https://github.com/databrickslabs/mosaic/blob/3a99cac38320a1332bafd51b540f6cf4b6183648/python/mosaic/api/raster.py#L399C1-L401C6). Judging from the other API implementations, the mapalgebra function is the only raster function that tries to pass two arguments to the `_to_java_column` function.
 
Environment: Databricks & PySpark

**To Reproduce**
1. Open a raster with Spark: `df = spark.read.format("gdal").option('driverName', 'GTiff').load("...")`
2. Call the mapalgebra function on the read tile: `df = df.withColumn("tile", mos.rst_mapalgebra(F.col("tile"), "{'calc': 'A>1'}"))`
4. See error `TypeError: _to_java_column() takes 1 positional argument but 2 were given`

**Additional context**
```
TypeError                                 Traceback (most recent call last)
File <command-1005030854969099>, line 4
      2 mounted_file = mounted_files[0]
      3 df = spark.read.format("gdal").option('driverName', 'GTiff').load(mounted_file.path)
----> 4 df = df.withColumn("tile", mos.rst_mapalgebra(F.col("tile"), "{'calc': 'A>1'}"))

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-98689a5f-dc91-4a79-9400-d1f66b035d25/lib/python3.10/site-packages/mosaic/api/raster.py:400, in rst_mapalgebra(raster_tile, json_spec)
    385 def rst_mapalgebra(raster_tile: ColumnOrName, json_spec: ColumnOrName) -> Column:
    386     """
    387     Parameters
    388     ----------
   (...)
    397 
    398     """
    399     return config.mosaic_context.invoke_function(
--> 400         "rst_mapalgebra", pyspark_to_java_column(raster_tile, json_spec)
    401     )

TypeError: _to_java_column() takes 1 positional argument but 2 were given
```

**Comment by sllynn** [comment]
Thanks for reporting the bug @ratteripenta. We'll look to fix this in the next release.

In the meantime, please call the SQL function directly using `pyspark.sql.functions.expr` function, e.g.

``` python
from pyspark.sql.functions import expr
cmd = """rst_mapalgebra(tile, "{'calc': 'A>1'}")"""
new_df = df.withColumn("new_tile", expr(cmd))
```

(or something along those lines)

@mjohns-databricks Looks like we need to review the python bindings / improve the test coverage.
