### ISSUE TITLE
grid_tessellateexplode, grid_tessellate

### ISSUE THREAD

**Issue by tony189** [databrickslabs/mosaic#572]
Hi!

It would be really usefull if you could chose to retrieve just the indexes ineastead the whole chip array in these functions to have a similar result to polyfill.

Thanks for your work

**Comment by sllynn** [comment]
Hi Tony. We have the `grid_polyfill` function ([docs](https://databrickslabs.github.io/mosaic/api/spatial-indexing.html#grid-polyfill)), if that's what you're after? Or do you want the set of indexes that 'covers' the geometry? In which case, there's a native H3 function you can use documented [here](https://docs.databricks.com/en/sql/language-manual/functions/h3_coverash3.html)

**Comment by tony189** [comment]
yes, that worked. 

Thank you
