### ISSUE TITLE
DBK 14.X

### ISSUE THREAD

**Issue by tony189** [databrickslabs/mosaic#590]
Hi,

I have the requirement to use DBK 14.X or higher. Is there a way to use mosaic with those versions?

**Comment by sllynn** [comment]
Hi Tony. 

Short answer is: we'll start on compatibility with 14.x once the next release is complete (i.e. 0.4.3 will still be locked to the 13 series DBRs).

I appreciate that is going to make things difficult for many users in your position so please accept my apologies there. Keeping pace with our engineering team is quite a challenge as you can imagine!
